### ISSUE TITLE
cache key as filename 

### ISSUE THREAD

**Issue by amit777** [hotelde/node-cache-manager-fs#20]
Hi, I was wondering if there was any particular reason to use the UUID method for generating the .dat files?  I noticed an issue when I run in cluster mode, each cluster process seems to generate it's own file in the cache directory so there are duplicates.

I was going to create a pull request for an optional flag to use the cache key as the filename.  Is there something obviously bad I'm missing about this idea?  Very long cache keys would have a problem or if the keys contained special characters and such.

Thanks for creating this!

**Comment by Mar-Pfa** [comment]
Hm... too long ago, to remember why I
coded it like that, create a pull request and i‘ll merge/publish it:-)

**Comment by Mar-Pfa** [comment]
after thinking again the reason was really the "long filenames" and "bad characters" situation. the cache is designed to run as "singleton" - currently there is no support for running multiple instances of the cache targeting the same file storage on disk.
Added a comment in README.md about that limitation
