### ISSUE TITLE
Does not refill cache on startup

### ISSUE THREAD

**Issue by Jakobud** [hotelde/node-cache-manager-fs#9]
No matter if I have `preventfill` true or false, every time I restart my script, the library does not fetch values from the existing cache on the filesystem. Here is some example code:

```
var cacheManager = require('cache-manager');
var fsStore = require('cache-manager-fs');
var cache = cacheManager.caching({
    store: fsStore, options: {
      ttl: 60*60,
      maxsize: 1000*1000*1000,
      fillcallback: function(){
        console.log('done filling from cache');
      }
    }
  });

var ttl = 30;

function getUser(id, cb) {
    console.log("Returning user from slow database.");
    setTimeout(function () {
        cb(null, {id: id, name: 'Bob'});
    }, 5000);
}

var userId = 123;
var key = 'user_' + userId;

cache.wrap(key, function (cb) {
    getUser(userId, cb);
}, {ttl: ttl}, function (err, user) {
    console.log(user);

    cache.wrap(key, function (cb) {
        getUser(userId, cb);
    }, function (err, user) {
        console.log(user);
    });
});
```

Every time I run my script.js, the `getUser()` method is called (which takes 5 seconds). It never seems to repopulate the cache on startup.

Am I missing something really obvious here?

**Comment by Jakobud** [comment]
I'm messing with your code a bit. The `DiskStore.prototype.intializefill` seems to be finding the .dat file and finding the values and it sets it in `this.collection`, but it still doesn't seem to work with the above code.

**Comment by gofreddo** [comment]
The problem is a race condition.  You are calling wrap before the cache is filled.  You have to wait for the fillcallback before you can allow a call to wrap.  The solution is to  wrap cacheManager.caching in a promise that is resolved when the diskcache is filled.  For example:

'use strict';
const rp = require('request-promise');
const cacheManager = require('cache-manager');
const fsStore = require('cache-manager-fs');

const _getFileNames = (opts) => {

  return new Promise((resolve, reject) => {

```
const options = {
  uri: opts.uri,
  auth: opts.auth,
  json: true,
  timeout: 2 * 60 * 1000,
};

return rp(options)
  .then((reponse) => {
    return resolve(reponse);
  })
  .catch((error) => {
    return reject(error);
  });
```

  });
};

const diskCachePromise = () => {
  return new Promise((resolve) => {
    const diskCache = cacheManager.caching(
      {
        store: fsStore,
        options: {
          ttl: 60 \* 60 \* 24 /\* seconds */,
          path: 'diskcache',
          preventfill: false,
          fillcallback: () => resolve(diskCache),
        },
      });
  });
}

const diskCache = diskCachePromise();

const getFileNames = (opts) => {
  return new Promise((resolve, reject) => {

```
diskCache.then((diskCache) => {
  diskCache.wrap('getFileNames', () => {
    return _getFileNames(opts);
  })
    .then((result) => {
      return resolve(result);
    })
    .catch((error) => {
      return reject(error);
    });

});
```

  });
};

module.exports = {
  getFileNames,
};

**Comment by rossvz** [comment]
This was also the issue I was running into. I created a simplified version of the above code: 
```
const initCache = () =>
  new Promise((resolve, reject) => {
    memoryCache = cacheManager.caching({
      store: fsStore,
      path: 'cache',
      ttl: 12 * 60 * 60,
      preventfill: false,
      reviveBuffers: false,
      fillcallback: data => {
        resolve()
      }
    })
  })
```

And I call that in my app like so

```
class MyClass {
   constructor(){
       initCache().then( //do some other stuff  ) 
   }
}

**Comment by rossvz** [comment]
This was also the issue I was running into. I created a simplified version of the above code: 
```
const initCache = () =>
  new Promise((resolve, reject) => {
    memoryCache = cacheManager.caching({
      store: fsStore,
      path: 'cache',
      ttl: 12 * 60 * 60,
      preventfill: false,
      reviveBuffers: false,
      fillcallback: data => {
        resolve()
      }
    })
  })
```

And I call that in my app like so

```
class MyClass {
   constructor(){
       initCache().then( //do some other stuff  ) 
   }
}

**Comment by websocket98765** [comment]
@rossvz 's post is helpful. I assume that only happens once data size reaches a certain size to lose the race condition. The second part can be written as `await initCache();` too within an async function.

Another thing to know is that diskCache does not support `mget()`. It will fail without an error message.

This was hard to diagnose because I set up a multiCache using a memoryCache (which worked) and a diskCache (which didn't). Switching my cache fetch from `mget()`, to a loop using `get()` allowed disk cache to work and was needed to get data pre-filling from disk working.

**Comment by Mar-Pfa** [comment]
the DiskCache is intended to run as a "singleton" - only one instance at one time and the api is running based on callbacks - no async, no promises... added that into the readme
